In [2]:
%matplotlib inline
import numpy as np

Matplotlib is building the font cache; this may take a moment.


# Lab-2: GEOMETRY & NEAREST NEIGHBORS 
- Breakdown weightage for each part of the question is given.
- You can access class notes and library documentations.

## 1. Euclidean Norm (10 + 10 + 20 + 10 + 10) 
The first task for today will be to write functions to compute distances in different orders of complexity.

In [238]:
np.random.seed(2)
x_a, x_b = (np.random.rand(i, 2) for i in (2, 3))
x_c, x_d = (np.random.rand(i, 100) for i in (125, 150))

In [239]:
x_a, x_b

(array([[0.4359949 , 0.02592623],
        [0.54966248, 0.43532239]]),
 array([[0.4203678 , 0.33033482],
        [0.20464863, 0.61927097],
        [0.29965467, 0.26682728]]))

In [240]:
x_a.ndim, x_a.shape, x_a.shape[0]

(2, (2, 2), 2)

In [241]:
for val in x_a:
    print(val)

[0.4359949  0.02592623]
[0.54966248 0.43532239]


In [242]:
for val in x_b:
    print(val)

[0.4203678  0.33033482]
[0.20464863 0.61927097]
[0.29965467 0.26682728]


### a.

### 3 For loops for traversing the x matrix, y matrix and then the rows of these matrices, since their dimensions are same. Then saved the square of the differences of the dimensions in a temporary array and then stored these arrays in the final result dist

In [243]:
def pairwise_1(x, y):
    """
    Find pairwise euclidean distance using three for loops
    """
    # x is 2*2
    # y is 3*2
    dist = np.empty((x.shape[0], y.shape[0]))
    i = 0
    
    for val1 in x:
        temp = []
        for val2 in y:
            distance = 0
            for k in range(val1.shape[0]):
                dim1 = val1[k]
                dim2 = val2[k]
                distance = distance + (dim1 - dim2) ** 2
            temp.append(distance ** (1/2))
        dist[i] = temp
        i = i + 1
    
    return dist
             
#raise NotImplementedError

In [244]:
pairwise_1(x_a, x_b) #checking my function's output

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

In [245]:
pairwise_1(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### b.

In [246]:
for val in x_a:
    print(val)

[0.4359949  0.02592623]
[0.54966248 0.43532239]


In [247]:
for val in x_b:
    print(val)

[0.4203678  0.33033482]
[0.20464863 0.61927097]
[0.29965467 0.26682728]


In [248]:
def pairwise_2(x, y):
    """
    Find pairwise euclidean distance using two for loops
    """
    dist = np.empty((x.shape[0], y.shape[0]))
    i = 0
    for val1 in x:
        j = 0
        for val2 in  y:
            temp = []
            dist[i][j] = np.sum((val1 - val2) ** 2) ** (1/2)
            #print(dist[i][j])
            j = j + 1
        i = i + 1
    return dist
    #raise NotImplementedError

In [249]:
pairwise_2(x_a, x_b) #checking my function's output

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

In [250]:
pairwise_2(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### c.

In [251]:
def pairwise_3(x, y):
    """
    An optimize solution with no for loops
  
    """
    dist_mat = np.sum((x[:, None] - y) ** 2, axis = -1) ** (1/2)
    return dist_mat
    
    #raise NotImplementedError

In [252]:
pairwise_3(x_a, x_b) #checking my function's output

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

In [253]:
pairwise_3(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### d.

In [254]:
# Compute distance using euclidean distance from scipy library(you can only refer the scipy documentation)
from scipy.spatial import distance_matrix 
def scipy_version(x, y):
    """
    A solution using scipy
    """
    dist = distance_matrix(x, y, p=2)
    return dist
    #raise NotImplementedError

In [255]:
scipy_version(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### e.

In [256]:
# Now compare all 4 method's runtime using inbuilt timeit function for 7 runs.
methods = [
    pairwise_1,
    pairwise_2,
    pairwise_3,
    scipy_version,
]
#TODO: Compute the run time(r) of all methods above
import timeit
%timeit -n100 -r7 pairwise_1(x_a, x_b)
%timeit -n100 -r7 pairwise_2(x_a, x_b)
%timeit -n100 -r7 pairwise_3(x_a, x_b)
%timeit -n100 -r7 scipy_version(x_a, x_b)

8.36 μs ± 1.23 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
19.9 μs ± 731 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)
5.99 μs ± 1.82 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
8.42 μs ± 2.18 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [257]:
# Now compare all 4 method's runtime using inbuilt timeit function for 7 runs.
methods = [
    pairwise_1,
    pairwise_2,
    pairwise_3,
    scipy_version,
]
#TODO: Compute the run time(r) of all methods above

In [258]:
#print best values of time(in s) for all methods, out of the 7 runs.
setup = '''import numpy as np 
from __main__ import pairwise_1, x_a, x_b, pairwise_2, pairwise_3, scipy_version
'''
print(min(timeit.Timer("pairwise_1(x_a, x_b)", setup=setup).repeat(7, 100)))
print(min(timeit.Timer("pairwise_2(x_a, x_b)", setup=setup).repeat(7, 100)))
print(min(timeit.Timer("pairwise_3(x_a, x_b)", setup=setup).repeat(7, 100)))
print(min(timeit.Timer("scipy_version(x_a, x_b)", setup=setup).repeat(7, 100)))


0.000745400000596419
0.001936500000738306
0.0004102000002603745
0.0007542999992438126


## 2. KNN (10 + 20 + 10)
Next we are going to implement KNN algorithm from scratch

### a.

### The function below is storing the distances and the labels in the dictionary. Then the distances are sorted and the sorted labels are returned

In [155]:
# sort elements of matrix and corresponding labels in ascending order.
def get_sorted_train_labels(distance_matrix, labels):
    sorted_labels = np.empty(distance_matrix.shape)
    #print(sorted_labels.shape[0], sorted_labels.shape[1])
    j = 0
    
    for row in range(distance_matrix.shape[0]):
        dict = {}
        for i in range(distance_matrix.shape[1]):
            dict[distance_matrix[row][i]] = y_train[i]
            
        dist_list = list(dict.keys())
        dist_list.sort()
        for ele in range(len(dist_list)):
            sorted_labels[j][ele] = int(dict[dist_list[ele]])    
        j = j + 1

        
    return sorted_labels
        
    #raise NotImplementedError

In [112]:
# test cases
x_test = np.array([[1,2,3] , [-4,5,-6]])
x_train = np.array([[0,0,0], [1,2,3], [4,5,6], [-4, 4, -6]]) 
y_train = np.array([[1, 1, 2, 3]]).T  #labels

In [113]:
# Here, we are comparing the distance computed by different methods if they are similar or not.
np.isclose(pairwise_1(x_test, x_train), pairwise_2(x_test, x_train)) 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [114]:
np.isclose(pairwise_2(x_test, x_train), pairwise_3(x_test, x_train))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [115]:
distance_matrix = pairwise_3(x_test, x_train)

In [116]:
print(distance_matrix)

[[ 3.74165739  0.          5.19615242 10.48808848]
 [ 8.77496439 10.72380529 14.4222051   1.        ]]


In [117]:
np.shape(distance_matrix)

(2, 4)

In [156]:
sorted_labels = get_sorted_train_labels(distance_matrix, y_train)
sorted_labels

C:\Users\Guest User\AppData\Local\Temp\ipykernel_11108\4063489250.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  sorted_labels[j][ele] = int(dict[dist_list[ele]])


array([[1., 1., 2., 3.],
       [3., 1., 1., 2.]])

In [157]:
# sorting distance computations and their corresponding labels.
sorted_train_labels = get_sorted_train_labels(distance_matrix, y_train)

C:\Users\Guest User\AppData\Local\Temp\ipykernel_11108\4063489250.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  sorted_labels[j][ele] = int(dict[dist_list[ele]])


In [20]:
print(sorted_train_labels)

[[1 1 2 3]
 [3 1 1 2]]


In [158]:
print("Closest 3 classes for first element from set X: {}".format(sorted_train_labels[0, :3]))

Closest 3 classes for first element from set X: [1. 1. 2.]


In [21]:
print("Closest 3 classes for first element from set X: {}".format(sorted_train_labels[0, :3]))

Closest 3 classes for first element from set X: [1 1 2]


### b.

### The function below is traversing through the labels matrix and for each test data point, it is storing the occurences of the top k labels in the dictionary. Then the label with maximum number of occurences is stored as the final label. If 2 labels have equal number of occurences then the label with smaller numerical value is stored in final

In [233]:
# First arrange the label sequence and then find the mode of k labels.
def get_mode_of_labels(labels, k):
    """
    Compute the mode of k labels
    """
    
    #print(labels)
    final_labels = []
    for row in labels:
        dict = {}
        #print(row)
        for j in row:
            #print(j)
            dict[j] = 0
            
        #print(len(row))
        for i in range(len(row)):
            if (i == (k - 1)):
                #print(i)
                break
            else:
                dict[row[i]] = dict[row[i]] + 1
                #print(dict[row[i]])

        maxm = 0
        label = 0   
        #print(dict)
        for key in dict.keys():
            if(dict[key] > maxm):
                label = key
                maxm = dict[key]
            elif(dict[key] == maxm):
                if(label > key or label == 0):
                    label = key
                
        #print(label)
        final_labels.append(int(label))
        #print(final_labels)

    #print(final_labels)
    return final_labels
    
   # raise NotImplementedError

### c.

In [234]:
# Now, using the functions created above, build a KNN.
def predict(x_test, x_train, y_train, k, distance_function):

    final_labels = []
    
    dist_mat = pairwise_3(x_test, x_train)
    get_sorted_labels = get_sorted_train_labels(dist_mat, y_train)
    final_labels = get_mode_of_labels(get_sorted_labels, k)
    return final_labels
   # raise NotImplementedError

In [235]:
prediction = predict(x_test, x_train, y_train, 3, pairwise_3)

C:\Users\Guest User\AppData\Local\Temp\ipykernel_11108\4063489250.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  sorted_labels[j][ele] = int(dict[dist_list[ele]])


In [236]:
print(prediction)

[1, 1]


In [25]:
print(prediction)

[1 1]
