In [1]:
%matplotlib inline
import numpy as np

# Lab-2: GEOMETRY & NEAREST NEIGHBORS 
- Breakdown weightage for each part of the question is given.
- You can access class notes and library documentations.

## 1. Euclidean Norm (10 + 10 + 20 + 10 + 10) 
The first task for today will be to write functions to compute distances in different orders of complexity.

In [2]:
np.random.seed(2)
x_a, x_b = (np.random.rand(i, 2) for i in (2, 3))
x_c, x_d = (np.random.rand(i, 100) for i in (125, 150))

### a.

In [1]:
def pairwise_1(x, y):
    """
    Find pairwise euclidean distance using three for loops
    """
    
    raise NotImplementedError

In [4]:
pairwise_1(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### b.

In [5]:
def pairwise_2(x, y):
    """
    Find pairwise euclidean distance using two for loops
    """
    raise NotImplementedError

In [6]:
pairwise_2(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### c.

In [7]:
def pairwise_3(x, y):
    """
    An optimize solution with no for loops
  
    """
    raise NotImplementedError

In [ ]:
pairwise_3(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### d.

In [8]:
# Compute distance using euclidean distance from scipy library(you can only refer the scipy documentation)
def scipy_version(x, y):
    """
    A solution using scipy
    """
    raise NotImplementedError

In [9]:
scipy_version(x_a, x_b)

array([[0.30480944, 0.6368509 , 0.27680674],
       [0.1665518 , 0.39098802, 0.30148716]])

### e.

In [10]:
# Now compare all 4 method's runtime using inbuilt timeit function for 7 runs.
methods = [
    pairwise_1,
    pairwise_2,
    pairwise_3,
    scipy_version,
]
#TODO: Compute the run time(r) of all methods above

1.39 s ± 48.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
178 ms ± 2.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
20.7 ms ± 827 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.55 ms ± 37.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
#print best values of time(in s) for all methods, out of the 7 runs.

[1308.920344003127, 176.15674999979092, 19.240979079913814, 1.5101509009982692]

## 2. KNN (10 + 20 + 10)
Next we are going to implement KNN algorithm from scratch

### a.

In [12]:
# sort elements of matrix and corresponding labels in ascending order.
def get_sorted_train_labels(distance_matrix, labels):
    
    raise NotImplementedError

In [13]:
# test cases
x_test = np.array([[1,2,3] , [-4,5,-6]])
x_train = np.array([[0,0,0], [1,2,3], [4,5,6], [-4, 4, -6]]) 
y_train = np.array([[1, 1, 2, 3]]).T  #labels

In [14]:
# Here, we are comparing the distance computed by different methods if they are similar or not.
np.isclose(pairwise_1(x_test, x_train), pairwise_2(x_test, x_train)) 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
np.isclose(pairwise_2(x_test, x_train), pairwise_3(x_test, x_train))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
distance_matrix = pairwise_3(x_test, x_train)

In [17]:
print(distance_matrix)

[[ 3.74165739  0.          5.19615242 10.48808848]
 [ 8.77496439 10.72380529 14.4222051   1.        ]]


In [18]:
np.shape(distance_matrix)

(2, 4)

In [19]:
# sorting distance computations and their corresponding labels.
sorted_train_labels = get_sorted_train_labels(distance_matrix, y_train)

In [20]:
print(sorted_train_labels)

[[1 1 2 3]
 [3 1 1 2]]


In [21]:
print("Closest 3 classes for first element from set X: {}".format(sorted_train_labels[0, :3]))

Closest 3 classes for first element from set X: [1 1 2]


### b.

In [22]:
# First arrange the label sequence and then find the mode of k labels.
def get_mode_of_labels(labels, k):
    """
    Compute the mode of k labels
    """
    
    raise NotImplementedError

### c.

In [23]:
# Now, using the functions created above, build a KNN.
def predict(x_test, x_train, y_train, k, distance_function):
    
    raise NotImplementedError

In [24]:
prediction = predict(x_test, x_train, y_train, 3, pairwise_3)

In [25]:
print(prediction)

[1 1]
