In [2]:
import numpy as np
import matplotlib.pyplot as plt

# K means on synthetic dataset
Your task is to implement kmeans from scratch without using any library other than nummpy, and matplotlib. Wherever necessary sklearn codes will be hardcoded and do not require any modifications. No need to modify any cells other than the defining functions.

In [27]:
#don't edit this cell
from sklearn.datasets._samples_generator import make_blobs
np.random.seed(0)
X, y = make_blobs(n_samples=5000, centers=[[4,4], [-2, -1], [2, -3], [1, 1]], cluster_std=0.9)
X,y

(array([[-1.82150565,  0.07098024],
        [ 2.16732621, -2.93199608],
        [ 0.8465158 , -3.26075305],
        ...,
        [ 3.29772603,  4.24400152],
        [-1.69503125, -0.29979681],
        [-1.64362141,  0.63035513]]),
 array([1, 2, 2, ..., 0, 1, 1]))

In [28]:
def initialize_centroids(X, k):
    return NotImplementedError

# Validate initialize centroids function
k = len(np.unique(y))  
centroids = initialize_centroids(X, k)
print("Initialized Centroids Shape:", centroids.shape)

Initialized Centroids Shape: (4, 2)


In [29]:
# Function to calculate Euclidean distance
def euclidean_distance(a, b):
    return NotImplementedError

In [30]:
# General compute_distances function
def compute_distances(X, centroids, distance_metric):
    return NotImplementedError

distances = compute_distances(X, centroids, euclidean_distance)
print("Distances computed:")
print(distances.shape)
print(distances)

Distances computed:
[[6.85158316 4.80575695 2.49093749 1.35318702]
 [5.98995314 0.19027042 5.36079494 3.91950081]
 [6.90432455 1.28041433 4.14704654 3.48522393]
 ...
 [2.10767214 7.14814148 8.99260531 5.70280428]
 [6.87947335 4.48878653 2.26078065 1.25097632]
 [6.49883946 5.02692561 3.06415822 1.34684575]]


In [32]:
def assign_clusters(distances):
    return NotImplementedError

# Test assign_clusters
labels = assign_clusters(distances)
print("Cluster labels assigned:")
print(labels)

Cluster labels assigned:
<class 'NotImplementedError'>


In [34]:
def update_centroids(X, labels, k):
    return NotImplementedError

# Test update_centroids
new_centroids = update_centroids(X, labels, k)
print("Updated centroids:")
print(new_centroids.shape)
print(new_centroids)

Updated centroids:


AttributeError: type object 'NotImplementedError' has no attribute 'shape'

In [11]:
def has_converged(old_centroids, centroids):
    return NotImplementedError

# Test has_converged
converged = has_converged(centroids, new_centroids)
print("Has converged:")
print(converged)

Has converged:
False


In [36]:
# summing it all
def kmeans(X, k, max_iters=100,distance_metric=euclidean_distance):
    centroids = None
    for i in range(max_iters):
        NotImplementedError
    return labels, centroids

# Test kmeans end-to-end
# Run k-means on the training data
k = len(np.unique(y))  # Number of clusters
labels, centroids = kmeans(X, k)
assert labels.shape[0] == X.shape[0], "kmeans failed"
assert centroids.shape == (k, X.shape[1]), "kmeans failed"

AttributeError: type object 'NotImplementedError' has no attribute 'shape'

In [26]:
# Visualize the centroids

In [15]:
def match_labels(y_true, y_pred,  num_classes):
    return NotImplementedError

# Get the matched labels
y_pred_matched = match_labels(y, labels, k)

In [ ]:
# print accuracy

# Now, on time series data - You are free to explore kmeans++ and DTW for better accuracy

In [17]:
# Load the training data and test data

In [18]:
# Basic summary statistics
print("Number of time series:", len(data_train))
print("Number of unique classes:", len(np.unique(data_train[:,0])))
print("Time series length:", len(data_train[0,1:]))

Number of time series: 23
Number of unique classes: 2
Time series length: 136


In [20]:
k = len(np.unique(y_train))  # Number of clusters
labels_train, centroids_train = kmeans(X_train, k)
assert labels_train.shape[0] == X_train.shape[0], "kmeans failed"
assert centroids_train.shape == (k, X_train.shape[1]), "kmeans failed"

In [25]:
# Visualize the centroids

In [24]:
# Evaluate the clustering on the test data